title: SeptiSearch
description: Detailed information on using the SeptiSearch database and site
theme: just-the-docs

url: https://hancockinformatics.github.io/SeptiSearchTutorial

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/hancockinformatics/SeptiSearchTutorial
